<?php

return [
    'magnit' => [
        'stores_url' => env('MAGNIT_STORES_URL', 'https://magnit.ru/webgate/v1/stores-facade/search/detail'),
        'goods_url' => env('MAGNIT_GOODS_URL', 'https://magnit.ru/webgate/v2/goods/search'),
        'catalog_url' => env('MAGNIT_CATALOG_URL', 'https://magnit.ru/catalog'),
        'user_agent' => env('MAGNIT_USER_AGENT', 'Mozilla/5.0'),
        'origin' => env('MAGNIT_ORIGIN', 'https://magnit.ru'),
        'delivery_type' => env('MAGNIT_DELIVERY_TYPE', 'DELIVERY_TYPE_PICKUP'),
        'accept_language' => env('MAGNIT_ACCEPT_LANGUAGE', 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7'),
        'device_id' => env('MAGNIT_DEVICE_ID'),
        'baggage' => env('MAGNIT_BAGGAGE'),
        'goods_store_type' => env('MAGNIT_GOODS_STORE_TYPE'),
        'raw_cookie_header' => env('MAGNIT_RAW_COOKIE_HEADER'),
        'goods_request_delay_ms' => (int) env('MAGNIT_GOODS_REQUEST_DELAY_MS', 2000),
        'max_items_per_category' => (int) env('MAGNIT_MAX_ITEMS_PER_CATEGORY', 150),
        'store_delay_ms' => (int) env('MAGNIT_STORE_DELAY_MS', 2500),
        'category_delay_ms' => (int) env('MAGNIT_CATEGORY_DELAY_MS', 900),
        'page_delay_min_ms' => (int) env('MAGNIT_PAGE_DELAY_MIN_MS', 900),
        'page_delay_max_ms' => (int) env('MAGNIT_PAGE_DELAY_MAX_MS', 1800),
        'timeout' => (int) env('MAGNIT_TIMEOUT', 30),
        'connect_timeout' => (int) env('MAGNIT_CONNECT_TIMEOUT', 20),
        'retry_attempts' => (int) env('MAGNIT_RETRY_ATTEMPTS', 3),
        'retry_backoff_ms' => (int) env('MAGNIT_RETRY_BACKOFF_MS', 1200),
        'goods_use_curl_binary' => env('MAGNIT_GOODS_USE_CURL_BINARY', false),
        'curl_fallback_enabled' => env('MAGNIT_CURL_FALLBACK_ENABLED', true),
        'curl_binary' => env('MAGNIT_CURL_BINARY', 'curl.exe'),
        'store_regions' => [
            'novokuznetsk' => [
                ['lat1' => 53.8727, 'lon1' => 86.8704, 'lat2' => 53.6473, 'lon2' => 87.2796],
            ],
            'moscow' => [
                ['lat1' => 56.0, 'lon1' => 37.0, 'lat2' => 55.4, 'lon2' => 38.3],
            ],
        ],
        'store_region' => env('MAGNIT_STORE_REGION'),
        'store_boxes' => json_decode(env('MAGNIT_STORE_BOXES', '[{"lat1":53.8727,"lon1":86.8704,"lat2":53.6473,"lon2":87.2796}]'), true) ?: [],
    ],
    'metro' => [
        'api_url' => env('METRO_API_URL', 'https://api.metro-cc.ru/products-api/graph'),
        'tradecenters_url' => env('METRO_TRADECENTERS_URL', 'https://api.metro-cc.ru/api/v1/C98BB1B547ECCC17D8AEBEC7116D6/tradecenters'),
        'default_store_id' => (int) env('METRO_DEFAULT_STORE_ID', 54),
        'default_trade_center_id' => (int) env('METRO_DEFAULT_TRADE_CENTER_ID', 55),
        'default_city' => env('METRO_DEFAULT_CITY'),
        'default_address' => env('METRO_DEFAULT_ADDRESS'),
    ],
    'lenta' => [
        'web_url' => env('LENTA_WEB_URL', 'https://lenta.com/'),
        'session_url' => env('LENTA_SESSION_URL', 'https://lenta.com/api/rest/sessionGet'),
        'regions_url' => env('LENTA_REGIONS_URL', 'https://lenta.com/api-gateway/v1/region/list'),
        'pickup_stores_url' => env('LENTA_PICKUP_STORES_URL', 'https://lenta.com/api-gateway/v1/stores/pickup/search'),
        'delivery_mode_url' => env('LENTA_DELIVERY_MODE_URL', 'https://lenta.com/api-gateway/v1/delivery/mode/set'),
        'categories_url' => env('LENTA_CATEGORIES_URL', 'https://lenta.com/api-gateway/v1/catalog/categories'),
        'items_url' => env('LENTA_ITEMS_URL', 'https://lenta.com/api-gateway/v1/catalog/items'),
        'client' => env('LENTA_CLIENT', 'angular_web_0.0.2'),
        'marketing_partner_key' => env('LENTA_MARKETING_PARTNER_KEY', 'mp300-b1de0bac2c257f3257bf5ef2eea4ecbc'),
        'version' => env('LENTA_VERSION', 'web-12.0.583'),
        'default_domain' => env('LENTA_DEFAULT_DOMAIN', 'moscow'),
        'app_cache_city' => env('LENTA_APP_CACHE_CITY'),
        'retail_brand' => env('LENTA_RETAIL_BRAND', 'lo'),
        'platform' => env('LENTA_PLATFORM', 'omniweb'),
        'device_os' => env('LENTA_DEVICE_OS', 'Web'),
        'device_web_platform' => env('LENTA_DEVICE_WEB_PLATFORM', 'desktop_web'),
        'device_id' => env('LENTA_DEVICE_ID'),
        'user_session_id' => env('LENTA_USER_SESSION_ID'),
        'session_token' => env('LENTA_SESSION_TOKEN'),
        'raw_cookie_header' => env('LENTA_RAW_COOKIE_HEADER'),
        'growthbook_user_id' => env('LENTA_GROWTHBOOK_USER_ID'),
        'growthbook_experiments' => env('LENTA_GROWTHBOOK_EXPERIMENTS'),
        'growthbook_cookie_experiments' => env('LENTA_GROWTHBOOK_COOKIE_EXPERIMENTS'),
        'experiments_header' => env('LENTA_EXPERIMENTS_HEADER'),
        'browser_user_agent' => env('LENTA_BROWSER_USER_AGENT'),
        'utk_marketing_group_token' => env('LENTA_UTK_MARKETING_GROUP_TOKEN'),
        'utk_sss_token' => env('LENTA_UTK_SSS_TOKEN'),
        'qrator_ssid' => env('LENTA_QRATOR_SSID'),
        'qrator_jsr' => env('LENTA_QRATOR_JSR'),
        'qrator_jsid' => env('LENTA_QRATOR_JSID'),
        'iap_uid' => env('LENTA_IAP_UID'),
        'agree_with_cookie' => env('LENTA_AGREE_WITH_COOKIE', 'true'),
        'delivery_mode' => env('LENTA_DELIVERY_MODE', 'pickup'),
        'page_size' => (int) env('LENTA_PAGE_SIZE', 600),
        'product_batch_size' => (int) env('LENTA_PRODUCT_BATCH_SIZE', 150),
        'retry_429_attempts' => (int) env('LENTA_RETRY_429_ATTEMPTS', 3),
        'timeout' => (int) env('LENTA_TIMEOUT', 30),
    ],
];
